AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "console-recorder"
Description: ""
Resources:
    lambdad835b85:
        Type: "AWS::Lambda::Function"
        Properties:
            Code: 
                ZipFile: "UEsDBAoAAAAAAG1VWE03NP4vpQAAAKUAAAASAAAAbGFtYmRhX2Z1bmN0aW9uLnB5aW1wb3J0IGpzb24KCmRlZiBsYW1iZGFfaGFuZGxlcihldmVudCwgY29udGV4dCk6CiAgICAjIFRPRE8gaW1wbGVtZW50CiAgICByZXR1cm4gewogICAgICAgICdzdGF0dXNDb2RlJzogMjAwLAogICAgICAgICdib2R5JzoganNvbi5kdW1wcygnSGVsbG8gZnJvbSBMYW1iZGEhJykKICAgIH0KUEsBAh4DCgAAAAAAbVVYTTc0/i+lAAAApQAAABIAAAAAAAAAAAAAAKSBAAAAAGxhbWJkYV9mdW5jdGlvbi5weVBLBQYAAAAAAQABAEAAAADVAAAAAAA="
            Description: ""
            FunctionName: "netflixtranscode"
            Handler: "lambda_function.lambda_handler"
            MemorySize: 128
            Role: "arn:aws:iam::571990649321:role/service-role/netflixtranscode-role-nys4wlhy"
            Runtime: "python3.6"
            Timeout: 3
            DeadLetterConfig: !Ref "AWS::NoValue"
            KmsKeyArn: ""
            TracingConfig: 
                Mode: "PassThrough"

    lambdae441ee6:
        Type: "AWS::Lambda::Function"
        Properties:
            Code: 
                ZipFile: "UEsDBAoAAAAAAG1VWE03NP4vpQAAAKUAAAASAAAAbGFtYmRhX2Z1bmN0aW9uLnB5aW1wb3J0IGpzb24KCmRlZiBsYW1iZGFfaGFuZGxlcihldmVudCwgY29udGV4dCk6CiAgICAjIFRPRE8gaW1wbGVtZW50CiAgICByZXR1cm4gewogICAgICAgICdzdGF0dXNDb2RlJzogMjAwLAogICAgICAgICdib2R5JzoganNvbi5kdW1wcygnSGVsbG8gZnJvbSBMYW1iZGEhJykKICAgIH0KUEsBAh4DCgAAAAAAbVVYTTc0/i+lAAAApQAAABIAAAAAAAAAAAAAAKSBAAAAAGxhbWJkYV9mdW5jdGlvbi5weVBLBQYAAAAAAQABAEAAAADVAAAAAAA="
            Description: ""
            FunctionName: "netflixtranscode"
            Handler: "lambda_function.lambda_handler"
            MemorySize: 128
            Role: "arn:aws:iam::571990649321:role/service-role/netflixtranscode-role-nys4wlhy"
            Runtime: "python3.6"
            Timeout: 3
            DeadLetterConfig: !Ref "AWS::NoValue"
            KmsKeyArn: ""
            TracingConfig: 
                Mode: "PassThrough"

    lambda22322c2:
        Type: "AWS::Lambda::Function"
        Properties:
            Code: 
                ZipFile: "UEsDBAoAAAAAAG1VWE03NP4vpQAAAKUAAAASAAAAbGFtYmRhX2Z1bmN0aW9uLnB5aW1wb3J0IGpzb24KCmRlZiBsYW1iZGFfaGFuZGxlcihldmVudCwgY29udGV4dCk6CiAgICAjIFRPRE8gaW1wbGVtZW50CiAgICByZXR1cm4gewogICAgICAgICdzdGF0dXNDb2RlJzogMjAwLAogICAgICAgICdib2R5JzoganNvbi5kdW1wcygnSGVsbG8gZnJvbSBMYW1iZGEhJykKICAgIH0KUEsBAh4DCgAAAAAAbVVYTTc0/i+lAAAApQAAABIAAAAAAAAAAAAAAKSBAAAAAGxhbWJkYV9mdW5jdGlvbi5weVBLBQYAAAAAAQABAEAAAADVAAAAAAA="
            Description: ""
            FunctionName: "netflixtranscode"
            Handler: "lambda_function.lambda_handler"
            MemorySize: 128
            Role: "arn:aws:iam::571990649321:role/service-role/netflixtranscode-role-nys4wlhy"
            Runtime: "python3.6"
            Timeout: 3
            DeadLetterConfig: !Ref "AWS::NoValue"
            KmsKeyArn: ""
            TracingConfig: 
                Mode: "PassThrough"

    lambda7bd04c7:
        Type: "AWS::Lambda::Function"
        Properties:
            Code: 
                ZipFile: "UEsDBAoAAAAAAG1VWE03NP4vpQAAAKUAAAASAAAAbGFtYmRhX2Z1bmN0aW9uLnB5aW1wb3J0IGpzb24KCmRlZiBsYW1iZGFfaGFuZGxlcihldmVudCwgY29udGV4dCk6CiAgICAjIFRPRE8gaW1wbGVtZW50CiAgICByZXR1cm4gewogICAgICAgICdzdGF0dXNDb2RlJzogMjAwLAogICAgICAgICdib2R5JzoganNvbi5kdW1wcygnSGVsbG8gZnJvbSBMYW1iZGEhJykKICAgIH0KUEsBAh4DCgAAAAAAbVVYTTc0/i+lAAAApQAAABIAAAAAAAAAAAAAAKSBAAAAAGxhbWJkYV9mdW5jdGlvbi5weVBLBQYAAAAAAQABAEAAAADVAAAAAAA="
            Description: ""
            FunctionName: "netflixtranscode"
            Handler: "lambda_function.lambda_handler"
            MemorySize: 128
            Role: "arn:aws:iam::571990649321:role/service-role/netflixtranscode-role-nys4wlhy"
            Runtime: "python3.6"
            Timeout: 3
            DeadLetterConfig: !Ref "AWS::NoValue"
            KmsKeyArn: ""
            TracingConfig: 
                Mode: "PassThrough"

    lambdaaa9c98d:
        Type: "AWS::Lambda::Function"
        Properties:
            Code: 
                ZipFile: "UEsDBAoAAAAAAG1VWE03NP4vpQAAAKUAAAASAAAAbGFtYmRhX2Z1bmN0aW9uLnB5aW1wb3J0IGpzb24KCmRlZiBsYW1iZGFfaGFuZGxlcihldmVudCwgY29udGV4dCk6CiAgICAjIFRPRE8gaW1wbGVtZW50CiAgICByZXR1cm4gewogICAgICAgICdzdGF0dXNDb2RlJzogMjAwLAogICAgICAgICdib2R5JzoganNvbi5kdW1wcygnSGVsbG8gZnJvbSBMYW1iZGEhJykKICAgIH0KUEsBAh4DCgAAAAAAbVVYTTc0/i+lAAAApQAAABIAAAAAAAAAAAAAAKSBAAAAAGxhbWJkYV9mdW5jdGlvbi5weVBLBQYAAAAAAQABAEAAAADVAAAAAAA="
            Description: ""
            FunctionName: "netflixtranscode"
            Handler: "lambda_function.lambda_handler"
            MemorySize: 128
            Role: "arn:aws:iam::571990649321:role/service-role/netflixtranscode-role-nys4wlhy"
            Runtime: "python3.6"
            Timeout: 3
            DeadLetterConfig: !Ref "AWS::NoValue"
            KmsKeyArn: ""
            TracingConfig: 
                Mode: "PassThrough"

    s34c69231:
        Type: "AWS::S3::Bucket"
        Properties:
            BucketName: "transcode-bucket-privateflix"

    s3ccabdb0:
        Type: "AWS::S3::Bucket"
        Properties:
            BucketName: "transcode-bucket-privateflix-uploads"

    cognitoidp6bafe7a:
        Type: "AWS::Cognito::UserPool"
        Properties:
            AdminCreateUserConfig: 
                AllowAdminCreateUserOnly: false
                UnusedAccountValidityDays: 7
            AutoVerifiedAttributes: 
              - "phone_number"
            DeviceConfiguration: 
                ChallengeRequiredOnNewDevice: false
                DeviceOnlyRememberedOnUserPrompt: true
            EmailConfiguration: 
                SourceArn: ""
                ReplyToEmailAddress: ""
            EmailVerificationMessage: "Your%20verification%20code%20is%20%7B%23%23%23%23%7D.%20"
            EmailVerificationSubject: "Your%20verification%20code"
            MfaConfiguration: "OFF"
            Policies: 
                PasswordPolicy: 
                    MinimumLength: 8
                    RequireUppercase: true
                    RequireLowercase: true
                    RequireNumbers: true
                    RequireSymbols: true
            Schema: []
            SmsConfiguration: 
                SnsCallerArn: ""
                ExternalId: ""
            SmsVerificationMessage: "Your%20verification%20code%20is%20%7B%23%23%23%23%7D.%20"
            UserPoolName: "privateflix"
            UserPoolTags: !Ref "AWS::NoValue"

    ec26de605a:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
            GroupDescription: "netflix_security_group"
            GroupName: "netflix_security_group"
            VpcId: "vpc-b5b014cd"

    ec2a6e1bce:
        Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
        Properties:
            Name: "netflix"
            Scheme: "internet-facing"
            SecurityGroups: 
              - "sg-029d9c0ac197e47d0"
            Subnets: 
              - "subnet-ad6657d4"
              - "subnet-8db8ebc6"
            Tags: []
            IpAddressType: "ipv4"
            Type: "application"

    ec201f1260:
        Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
        Properties:
            HealthCheckIntervalSeconds: 5
            HealthCheckPath: "/"
            HealthCheckProtocol: "HTTP"
            HealthCheckTimeoutSeconds: 4
            HealthyThresholdCount: 3
            Matcher: 
                HttpCode: "200-499"
            Name: "netflix-servers"
            Port: 80
            Protocol: "HTTP"
            TargetType: "instance"
            UnhealthyThresholdCount: 2
            VpcId: "vpc-b5b014cd"

    cloudformationd8aa47a:
        Type: "AWS::CloudFormation::Stack"
        Properties:
            NotificationARNs: []
            Parameters: 
              - 
                parameterKey: "BuilderPublicSubnet"
                parameterValue: "subnet-703b3b2a"
              - 
                parameterKey: "BuilderVPC"
                parameterValue: "vpc-b5b014cd"
              - 
                parameterKey: "CodeBuildEnvironment"
                parameterValue: "eb-python-2.6-amazonlinux-64:2.1.6"
              - 
                parameterKey: "NotificationEmailAddress"
                parameterValue: "adrian@adriandrummond.com"
              - 
                parameterKey: "ServiceName"
                parameterValue: "AMI-Builder"
            Tags: []
            TemplateURL: "https://s3-us-west-2.amazonaws.com/cf-templates-jfn2vy2a11bk-us-west-2/20190930ET-pipeline.yaml"

