########################################################################################################
########################################################################################################
#
#     Just run this file over and over
#
#
########################################################################################################
########################################################################################################

# Notes:

# https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html
#  


version: 0.2

env:
  variables:
    key1: "value1"
    key2: "value2"
phases:
  install:
    commands:
      - echo no install necessary
      # - command

  pre_build:
    commands:
      - pwd
      - ls -al 
      - echo $CODEBUILD_INITIATOR
      - CODEBUILD_INITIATOR_SERVICE="$(echo $CODEBUILD_INITIATOR | cut -d'/' -f1)"
      - CODEBUILD_INITIATOR_NAME="$(echo $CODEBUILD_INITIATOR | cut -d'/' -f2)"
      - echo $CODEBUILD_INITIATOR_NAME
      - PIPELINENAME=$CODEBUILD_INITIATOR_NAME
      - echo PIPELINENAME=
      - echo $PIPELINENAME      

      ## SET ENVIRONMENT VARIABLES
      - DEPLOYMENTVPCPARAMETERNAME=$PIPELINENAME-vpc-SSMparameterVPCID
      - DEPLOYMENTVPCPARAMETER=$(aws ssm get-parameter --name $DEPLOYMENTVPCPARAMETERNAME --region $AWS_REGION --output text --query 'Parameter.Value')

      - DBSUBNET1NAME=$PIPELINENAME-vpc-SSMparameterDBSUBNET1
      - DBSUBNET1=$(aws ssm get-parameter --name $DBSUBNET1NAME --region $AWS_REGION --output text --query 'Parameter.Value')

      - DBSUBNET2NAME=$PIPELINENAME-vpc-SSMparameterDBSUBNET2
      - DBSUBNET2=$(aws ssm get-parameter --name $DBSUBNET2NAME --region $AWS_REGION --output text --query 'Parameter.Value')

      - VPCSECURITYGROUPIDNAME=$PIPELINENAME-vpc-SSMparameterStreamaServerSG
      - VPCSECURITYGROUPID=$(aws ssm get-parameter --name $VPCSECURITYGROUPIDNAME --region $AWS_REGION --output text --query 'Parameter.Value')

      - MASTERUSERPASSWORDNAME=$PIPELINENAME-secret
      - MASTERUSERPASSWORD=$(aws ssm get-parameter --name $MASTERUSERPASSWORDNAME --region $AWS_REGION --output text --query 'Parameter.Value')



  build:
    commands:
      - cd deployment_pipeline/
      - aws cloudformation deploy --stack-name $CODEBUILD_INITIATOR_NAME-createdatabase --template-file cloudformation_createdatabase.yaml --parameter-overrides CIDRRangePrefix=10.250 MasterUserPassword=$MASTERUSERPASSWORD VpcId=$DEPLOYMENTVPCPARAMETER DatabaseName=streama VpcSecurityGroupId=$VPCSECURITYGROUPID DBSubnet1=$DBSUBNET1 DBSubnet2=$$DBSUBNET2 --capabilities CAPABILITY_IAM --tags createdby=adrian --no-fail-on-empty-changeset --debug

      # - aws ec2 describe-vpcs
      # - aws s3 ls
      # - command

  post_build:
    commands:
      - echo NO STEPS IN POST_BUILD stage
      # - command

# artifacts:
#   files:
#     # - location
#     # - location
#   discard-paths: yes
#   base-directory: location
# cache:
#   paths:
#     - path
#     - path












