AWSTemplateFormatVersion: 2010-09-09
Description: Polly Whitepapers VPC template.  Authors - AWS Study Gurus


Parameters:

  CIDRRangePrefix:
    Description: 'Provide a valid Class-B CIDR Block Range.'
    ConstraintDescription: 'Must provide the first two octets seperated by a period. ( Example: "10.250" )'
    Type: String
    AllowedPattern: '((\d{1,3})\.){1}\d{1,3}'
    MinLength: 3
    MaxLength: 7

  HostedZoneName:
    Description: 'Provide a valid internal Domain Name for the crawler.'
    ConstraintDescription: 'Must provide valid internal Domain Name. ( Example: "pollywhitepapers.com" )'
    Type: String
    Default: private.adrianws.com

  ProvisionNATgateways:
    Description: 'NAT Gateways are expensive for personal projects.  This is a feature to not create them'
    ConstraintDescription: 'true or false'
    Type: String
    Default: false

Conditions: 
  ProvisionNATgateways: !Equals [ !Ref ProvisionNATgateways, true ]

Resources:







